## Процент пациентов с хроническими заболеваниями для групп "есть ОПП/нет ОПП

In [12]:
import pandas as pd


def calc_chronic_ratio(df: pd.DataFrame):
    df = df.copy()

    # полные группы "есть ОПП/нет ОПП"
    group_1_all = df[(df["развитие_опп"] == 1)]
    group_2_all = df[(df["развитие_опп"] == 0)]

    # группы "есть ОПП/нет ОПП" и есть хроническое заболевание
    group_1_chronic = df[(df["развитие_опп"] == 1) & (df["есть_хроническое_заболевание"] == 1)]
    group_2_chronic = df[(df["развитие_опп"] == 0) & (df["есть_хроническое_заболевание"] == 1)]

    # размерность полных групп
    count_1_all = group_1_all.shape[0]
    count_2_all = group_2_all.shape[0]

    # размерность группы с хроническим заболеванием
    count_1_chronic = group_1_chronic.shape[0]
    count_2_chronic = group_2_chronic.shape[0]

    # подсчёт процентов внутри групп
    percent_1 = count_1_chronic / count_1_all * 100
    percent_2 = count_2_chronic / count_2_all * 100

    print(round(percent_1, 2), round(percent_2, 2))  # 96.97 98.28

def check_hbp_diagnosis(data: pd.DataFrame):
    for index, row in data.iterrows():
        hbp = row["хбп"]
        skf = row["скф_расч"]
        if skf > 90:
            if hbp != 0:
                return False
        if 60 <= skf < 90:
            if data["хбп"][index] != 1:
                return False
        if 30 <= skf < 60:
            if data["хбп"][index] != 3:
                return False
    return True


In [13]:
import pandas as pd
from utils.preformatting_data import *

data = preformat(pd.read_csv('../medics_1.csv', delimiter=',', encoding='utf-8'))

In [14]:
calc_chronic_ratio(data)

96.97 98.28


In [15]:
print(check_hbp_diagnosis(data))

False


Процент для групп с хроническими заболеваниями: Есть опп - 96.97, Нет опп - 98.28

Некоторые диагнозы были поставлены неправильно